# Generated by Django 4.1.6 on 2023-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constapp', '0004_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='buymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namt', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quan', models.IntegerField()),
            ],
        ),
    ]
