# Generated by Django 4.1.6 on 2023-02-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constapp', '0005_buymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buymodel',
            old_name='namt',
            new_name='nmat',
        ),
    ]
