# Generated by Django 4.1.6 on 2023-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constapp', '0006_rename_namt_buymodel_nmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('smat', models.CharField(choices=[('CEMENT', 'CEMENT'), ('STEEL', 'STEEL'), ('METAL', 'METAL'), ('SAND', 'SAND'), ('BRICK', 'BRICK'), ('TOOLS', 'TOOLS')], max_length=100)),
                ('image', models.ImageField(upload_to='constapp/static')),
                ('nmat', models.CharField(max_length=50)),
                ('quan', models.IntegerField()),
                ('per', models.CharField(choices=[('KG', 'KG'), ('SQUARE-FEET', 'SQUARE-FEET'), ('NUMBER', 'NUMBER'), ('HOUR', 'HOUR'), ('MINUTE', 'MINUTE')], max_length=50)),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=500)),
            ],
        ),
    ]
