# Generated by Django 4.1.6 on 2023-02-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constapp', '0008_macmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editpromodel',
        ),
    ]
