# Generated by Django 4.1.6 on 2023-02-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constapp', '0009_delete_editpromodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='buynowmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('nmat', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quan', models.IntegerField()),
            ],
        ),
    ]
